### ISSUE TITLE
신규예약 및 예약변경

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#11]
- https://github.com/opencloset/api.theopencloset.net/issues/1
- opencloset booking#visit

에서 사용될 것 입니다.

**Comment by aanoaa** [comment]
주문서는 사용자 의존성을 갖고 있습니다.
새로운 주문서를 만들기 전에 새로운 사용자를 만드는 방법을 제공해야 하는데,

사용자는 본인확인 절차를 거치고, 이메일은 한번 입력하면 변경할 수 없습니다.
휴대전화번호는 변경해도 되지만 변경하는 방법이 없습니다.

단순하게 생각하면 입력 값 그대로 새로운 사용자로 등록하는 방법이 있습니다.

주소지는 입력 값을 그대로 사용할 수 없고 지번주소나 도로명주소를 가지고 나머지 주소를 검색해서 올바르게 찾아서 넣어줘야 합니다.

- 주소ID (1234567890)
- 지번주소 (서울시 광진구 화양동 48-3)
- 도로명주소 (서울시 광진구 화양동 아차산로 213)
- 상세주소 (웅진빌딩 403호)

**Comment by aanoaa** [comment]
주문서를 새로 생성하는 것은 `box2boxed` 처럼 `null -> reservation` 주문서없음 에서 예약완료로 상태를 변경하는 행위와 비슷합니다.
이때에 동반된 작업들을 묶어서 처리하는 것은 의미가 있습니다.
필수로 필요한 것이 사용자정보인데, 이것을 위해서 사용자 정보를 만들기 위한 wrapper API 가 필요할지가 의문입니다.

    my $user = $rs->create({ name => '홍길동', email => 'gildong@theopencloset.net', ... });
    my $user = $user_api->create({ name => '홍길동', email => 'gildong@theopencloset.net', ... });

그냥 만들면 되거든요.

장점이라고 한다면..

- 입력에 대한 유효 값 검증

이 있을 수 있겠지만 Web app 에서 이미 유효값을 검증하니까 상관없습니다.

-------------------------------------------

user 및 user_info 는 알아서 만들고,

    $api->null2reservation($user, $params);

정도로 처리하는 것이 더 좋을 것 같습니다.

**Comment by aanoaa** [comment]
1. [ ] Improve OpenCloset::API::Order::reservated test code(1)
2. [ ] Migrate OpenCloset::Plugin::Helpers::transfer_order to OpenCloset::API::Order::transfer_order
3. [ ] Improve OpenCloset::API::Order::reservated test code(2)
4. [ ] visit/staff 에서 OpenCloset::API::Order::reservated 를 활용
5. [ ] 기능 테스트
6. [ ] 예약변경에 대해서 1 ~ 5 를 반복

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.0.6.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.0.6.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
이 모듈을 활용하도록 opencloset 을 변경해서 방문예약과 방문예약 변경을 테스트해보고 문제가 없다면 닫도록 하겠습니다.

**Comment by aanoaa** [comment]
직원예약을 고려한 버전
[OpenCloset-API-v0.1.0.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.0.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
@10001if 

방문예약 서비스에서 이 모듈을 활용해서 방문예약을 하도록 변경하고 적용하였습니다.
실제 서비스에서 혹시 문제가 생길까 걱정됩니다.

몇일간

- 방문예약
- 취업날개 예약
- 예약 후 문자메세지 전송

등에 대해 모니터링 하시고 문제가 발생하면 알려주세요.

**Comment by 10001if** [comment]
@aanoaa 네. 확인 후 문제가 발생하면 바로 말씀드리도록 하겠습니다.

**Comment by aanoaa** [comment]
https://github.com/opencloset/opencloset/issues/1426 에서 발견된건데,
의류착용일을 주문서에 입력하고 있지 않습니다.

예약완료 혹은 예약변경시점에 주문서에 의류착용일을 입력해주어야 합니다.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.5.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.5.tar.gz) 배포하였습니다.
