### ISSUE TITLE
서울시 쿠폰으로 방문예약시 발송되는 문자 수정

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#18]
https://github.com/opencloset/OpenCloset-Cron-SMS/issues/31 에서 옮깁니다.

<img width="527" alt="screenshot_20180222-104053" src="https://user-images.githubusercontent.com/17288038/36658734-450e1ece-1b15-11e8-9603-fd1a8960a8f5.png">

현재는 위와 같이 작년 내용으로 발송되고 있는데요,
아래와 같이 올해 내용으로 발송되도록 수정부탁드립니다. 

    [열린옷장] 2018 취업날개 서비스

    올해 면접정장 무료대여는 '서울시' 거주 중인 고교졸업예정자~34세를 대상으로 합니다.  아래 거주지 증빙 미지참시 무료 대여가 되지 않습니다. 

    1. 주민등록상 서울시 거주자인 경우 : 서울시 주소와 나이를 증명할 수 있는 신분증(주민등록증, 운전면허증, 등본)
    2. 서울소재 학교 재학생/졸업생인 경우 : 학생증/졸업증명서 + 서울거주 증명서류(본인명의 계약서, 수도전기 고지서 등)

    매회 이용시 증빙이 필요하며, 이용조건 증빙이 없는 경우 무료대여 서비스를 이용할 수 없음을 거듭 안내드립니다. 감사합니다.

- 가능하다면 제목의 "2018 취업날개 서비스" 부분은 볼드체나 컬러색으로 눈에 띄게 처리되면 좋겠습니다.

**Comment by aanoaa** [comment]
SMS 에서는 bold text 를 사용할 수 없습니다.
80자가 넘어가면 SMS 를 여러개 보내는 대신에 LMS 로 변환해서 보내지고 있기는 하지만,
이것은 SMS 발송대행업체 에서 자동으로 변환해서 보내는 것 입니다.
이 경우에는 확실히 LMS 로 전송될 것 이지만 LMS 에서 bold text 혹은 color text 를 지원하는지 여부는 모르겠습니다.

https://www.apistore.co.kr/api/apiView.do?service_seq=151&api_group_seq=18&api_info_seq=209

> 메시지의 내용 (90byte 초과 시 자동 lms로 전환 발송) 

MMS 로 발송하도록 하면 어떻게 방법이 있을 것 같긴하지만 현재 사용하는 서비스 대행업체에서의 지원여부가 불확실하고,
테스트 및 관련 모듈을 제작해야 합니다.(MMS 와 관련된 지식 학습도 필요)
배보다 배꼽이 큽니다.

우선 메세지를 바꾸겠습니다.
꼭 필요하다면 말씀해주세요.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.4.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.4.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
서버에 모듈을 설치하고 관련된 서비스를 재시작해주어야 합니다.

    $ closetpan -n OpenCloset::API
    $ ubic reload opencloset.staff
    $ ubic reload opencloset.visit

**Comment by aanoaa** [comment]
관련해서 opencloset repo 의

- templates/sms/employment-wing.txt.ep
- templates/sms/order-confirmed-1.txt.ep
- templates/sms/order-confirmed-2.txt.ep

등은 사용되지 않습니다.
OpenCloset::API 를 활용하도록 바꾸면서 혹시나 여전히 참조 되어 있는 서비스가 있을까 하여 남겨두었습니다.
조만간에 사용되지 않는 sms template 을 삭제해서 잘못 수정하는 일이 없도록 하겠습니다.

cc @keedi

**Comment by pingpongworks** [comment]
감사합니다. 볼드는 깨끗이 포기하겠습니다^^
