### ISSUE TITLE
 반납 완료시 발송되는 문자에 '온라인대여 안내' 추가

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#19]
https://github.com/opencloset/OpenCloset-Cron-SMS/issues/35

OpenCloset-Cron-SMS 는 예약된 메세지를 보내는 서비스이고,
반납 메세지는 OpenCloset-API 에서 전송합니다.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.6.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.6.tar.gz) 배포하였습니다.

**Comment by pingpongworks** [comment]
@aanoaa 지금 온라인대여한 후 반납을 해보았는데 메시지에 온라인대여 안내가 추가되어 있지 않습니다.

    [Web발신] 
    [열린옷장] 000 님의 의류가 정상적으로 반납되었습니다. 감사합니다.  

이렇게만 메시지가 오네요. 배포된 후 아직 적용이 되지 않은걸까요?

**Comment by aanoaa** [comment]
이게 좀 헛갈리실 수 있습니다.
OpenCloset-API를 포함하고 있는 것이, opencloset/opencloset 입니다.
OpenCloset-API 는 배포되었지만, opencloset/opencloset 에는 아직 새로운 버전이 포함되지 않았습니다.

재고관리의 다음버전에 수정되어서 배포됩니다.

https://github.com/opencloset/OpenCloset-Cron-SMS/issues/35#issuecomment-421707733

**Comment by pingpongworks** [comment]
네~ 다 이해하지는 못했지만 아직 배포되지 않았다는 말씀이죠?^^ 알겠습니다
