### ISSUE TITLE
[반납문자 수정] 오프라인 대여시 반납완료 안내문자 내용 수정

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#25]
https://github.com/opencloset/OpenCloset-Cron-SMS/issues/36

법률상담, 자신감컨설팅, 내공식탁, 열린사진관 등 정장 대여 이외에 열린옷장의 취준생 대상 프로그램이 다양해짐에 따라 대여자에게 취업준비에 필요한 프로그램 정보를 안내하고자 합니다. 
기존의 반납완료 안내 문자의 내용을 다음과 같이 수정하고자 합니다.  

    [Web발신]
    [열린옷장] 000 님의 의류가 정상적으로 반납되었습니다. 감사합니다.

    [택배대여 안내] 다음에는 집에서 편하게 온라인으로 주문하세요. 
    http://share.theopencloset.net/welcome  클릭하여 신청하시면 됩니다.

    [청년정보 안내] 청년과 취업을 응원하는 다양한 프로그램 진행 중입니다. 
    열린옷장 SNS를 팔로우하면 놓치지 않고 받을 수 있습니다.   
    https://www.instagram.com/opencloset_people/
    https://www.facebook.com/TheOpenCloset/

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.10.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.10.tar.gz) 배포하였습니다.

**Comment by aanoaa** [comment]
새로운 버전 설치하고 staff, visit 서비스 재시작 하였습니다.
지금부터 반납 문자메세지 내용이 변경될 것 입니다.

**Comment by aanoaa** [comment]
@pingpongworks 내용을 확인해보시고 바뀌었다면 닫아주세요.

**Comment by pingpongworks** [comment]
테스트를 통해 문자내용 수정 확인했습니다. 감사합니다~
