### ISSUE TITLE
결제대기 -> 대여

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#3]
[새로운 결제 및 반납 화면의 구성](https://github.com/opencloset/opencloset/issues/1277) 해결을 위해 우선되어야 합니다.

**Comment by aanoaa** [comment]
결제대기 상태의 주문서를 staff 서비스에서 열면 js 에서 몇가지 처리를 합니다.

- 대여일(`rental_date`) 를 변경합니다.(오늘 날짜로)
- 반납예정일(`target_date`) 를 변경합니다.(+4d 23:59:59)
- 반납희망일(`user_target_date`) 를 변경합니다.(+4d 23:59:59)
- 각 대여의류의 final_price 를 변경합니다
- 이건 뭔지 모르겠는데 `주문서 메모 5F` 가 덧붙여집니다.

        # 4번 방문했을때( 같은 메세지가 덧붙여짐 )
        2016-03-11 주문서 의류 요청합니다.
        2016-03-11 주문서 의류 요청합니다.
        2016-03-11 주문서 의류 요청합니다.
        2016-03-11 주문서 의류 요청합니다.

**Comment by aanoaa** [comment]
`결제대기` 상태의 주문서를 확인하려고 하는데 데이터가 변경되고 있어서 헛갈릴 여지가 있습니다.
(editable 을 사용해서 그런 것 같기도 하고..)

각종 컬럼들을 수시로 변경해줄 필요가 있습니다.
원하고자 하는 컬럼을 선택해서 수정하고 확인버튼을 누를때에만 변경되도록 하겠습니다.

js 의 의존성을 없애는 것이 더 유리할 것 같습니다.
대여일, 반납일등이 js 의 의존성을 가지고 있습니다.

**Comment by 10001if** [comment]
> 이건 뭔지 모르겠는데 주문서 메모 5F 가 덧붙여집니다.
> 
>   # 4번 방문했을때( 같은 메세지가 덧붙여짐 )
>   2016-03-11 주문서 의류 요청합니다.
>   2016-03-11 주문서 의류 요청합니다.
>   2016-03-11 주문서 의류 요청합니다.
>   2016-03-11 주문서 의류 요청합니다.

-> 저도 궁금했는데, 방문 횟수마다 같은 메세지가 덧붙여지고 있습니다.

**Comment by aanoaa** [comment]
대여중으로 변경되기 위해서는 추가 정보가 필요합니다.
이는 staff 이 입력하거나 시스템에서 자동으로 결정해야 합니다.

- 대여기간(default 3박 4일: +4d)
- 대여일(default: now)
- 결제방법

--------------------

이외에도 bestfit, 담당자, 메모, 반납방법등 많은 컬럼이 존재하지만
이것들은 주문서내용 변경과 관련이 있는 것이지
`결제대기 -> 대여중` 에 필요한 값들은 아닙니다.

**Comment by aanoaa** [comment]
기존 코드를 참고해서 `결제대기 -> 대여중` 으로 변경될때 어떠한 일이 일어나는지 확인해봤습니다.

- 주문서의 상태를 `대여중` 으로 변경
- 대여자에게 주문내용 및 반납안내 SMS 전송
- 대여자에게 기증이야기 SMS 전송
- 쿠폰의 상태를 변경
- 의류(clothes)의 상태를 `대여중` 으로 변경
- 주문내역 의류(order_detail)의 상태를 `대여중` 으로 변경

**Comment by aanoaa** [comment]
monitor 에 이벤트 알림하는 부분이 보이지 않습니다.
js 에서 처리하는게 아닌가 싶습니다.

아래작업이 추가되어야 합니다.

- 대여기간에 따라 반납희망일과 연장일을 변경
- 대여일을 저장(now)
- 결제방법을 저장
- monitor 에 이벤트 알림

**Comment by aanoaa** [comment]
최소한의 필요조건은 대여기간이 아닌가 싶습니다.

    주문서 A를 n일간 대여한다.

결제방법은 다른 컬럼들과 마찬가지로 취급합니다.
입력하면 있는거고 없으면 마는거고..

**Comment by aanoaa** [comment]
대여일과 착용일의 시간은 00:00:00 으로 넣고 있습니다.
반납예정일과 반납희망일의 시간은 23:59:59 으로 넣습니다.

**Comment by aanoaa** [comment]
주문서의 상태변경을 모듈화 하려던 시도가 있었습니다.
(제가 작업했는데 잊고 있었습니다)

`반납 -> 환불` 로 변경

https://github.com/opencloset/OpenCloset-Common/blob/develop/lib/OpenCloset/Common/OrderStatus.pm

**Comment by aanoaa** [comment]
메세지가 덧붙여지는 문제는 `GET /order/:id` 를 요청한 후에 js 에 의해서 발생하는 것 같습니다.
버그라고 생각되는 위 기능은 무시하고 진행했습니다.

**Comment by aanoaa** [comment]
`결제방법` 이 비어있는 주문서가 만들어질 수 있습니다.
결제방법이 비어있다면 결제가 되지 않도록 하거나 결제방법을 입력할 수 있는 옵션을 제공해야 하는게 아닌가 싶습니다.
