### ISSUE TITLE
예약직후에 서울시 쿠폰 대상자에게 문자발송

### ISSUE THREAD

**Issue by aanoaa** [opencloset/OpenCloset-API#31]
https://github.com/opencloset/opencloset/issues/1660

> 문자전송 대상자
> 
> 사용자정보의 주소지 : 서울
> 태어난해 : 1985~2002
> 대여목적 : 입사면접, 인턴면접
> 
> 위 요건에 해당되는 대여자는 방문예약 직후에 안내문자가 발송되면 좋겠습니다.

에게 아래 메세지를 보내야 합니다.

    [열린옷장] 서울시 무료대여 정보알림
    현재 서울시 청년을 위한 연 10회 무료 정장대여 "취업날개 서비스" 진행중입니다. 주소지, 입사면접 증빙 등 자격요건과 필요서류를 확인하시고 소중한 혜택을 누리시기 바랍니다.
    
    서울시 취업날개 바로가기 => http://bitly.kr/yw53

대상자들이 현장에서 서울시쿠폰 대상자임을 알게되면 예약을 취소하고 다시 예약하게 되는데,
이러한 번거로움을 줄이는 취지 입니다.

**Comment by aanoaa** [comment]
[OpenCloset-API-v0.1.13.tar.gz](https://cpan.theopencloset.net/STAFF@THEOPENCLOSET.NET/OpenCloset-API-v0.1.13.tar.gz) 배포하였습니다.

**Comment by pingpongworks** [comment]
아 배포된거네요. 제가 테스트해볼게요

**Comment by aanoaa** [comment]
이 배포랑 서비스 배포랑 다릅니다.
여기서 배포된 걸 가지고 서비스에서 가지고 와서 다시 배포 합니다.

서비스에는 아직 배포되지 않았습니다

**Comment by pingpongworks** [comment]
아 그런가봐요. 해보니까 안 오더라고요.
